include:
  - local: '/frontend/.gitlab-ci.base.yml'

variables:
  FRONTEND_COMPONENT: "frontend"
  FRONTEND_STORYBOOK_COMPONENT: "frontend_storybook"

# This job extracts FE version from the package.json and shares it in an env variable with following jobs
# The version is labeled with GIT ref slug
# FRONTEND_IMAGE is then used to deploy the app. If frontend image is also built, the var is then replaced
# with the pinned image version to prevent deploying versions from different pipelines.
frontend-version:
  image: "$BUILDER_IMAGE"
  stage: version
  script:
    - cd frontend
    - VERSION=$(jq -r '.version' package.json)
    - FRONTEND_VERSION=$VERSION-$GIT_SLUG
    - echo "FRONTEND_VERSION=$FRONTEND_VERSION" > ci.env
    - echo "FRONTEND_IMAGE=$DOCKER_REPOSITORY/$FRONTEND_COMPONENT:$FRONTEND_VERSION" >> ci.env
    - FRONTEND_STORYBOOK_VERSION=$GIT_SLUG
    - echo "FRONTEND_STORYBOOK_VERSION=$FRONTEND_STORYBOOK_VERSION" >> ci.env
    - echo "FRONTEND_STORYBOOK_IMAGE=$DOCKER_REPOSITORY/$FRONTEND_STORYBOOK_COMPONENT:$FRONTEND_STORYBOOK_VERSION" >> ci.env
    - cat ci.env
  artifacts:
    reports:
      dotenv: frontend/ci.env

frontend-test-plop-templates:
  image: "$FRONTEND_BASE_IMAGE"
  stage: test
  allow_failure: false
  variables:
    NODE_ENV: test
  script:
    - cd frontend
    - yarn install --cache-folder .yarn
    - echo "${CI_COMMIT_TITLE}\n\n${CI_COMMIT_DESCRIPTION}" | node_modules/.bin/commitlint
    - yarn test:generate
  cache: &frontend-cache
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
    - frontend/node_modules/
    - frontend/yarn.lock
  only:
    changes:
      - frontend/.plop-templates/**/*
      - frontend/package.json

frontend-image:
  extends: .kaniko-build-template
  dependencies: ["frontend-version"]
  needs: ["frontend-version"]
  variables:
    COMPONENT: $FRONTEND_COMPONENT
    VERSION: $FRONTEND_VERSION
    CONTEXT: "frontend"
    DOCKERFILE: "frontend/Dockerfile"
  before_script:
    # it needs to be here due to a limit on gitlab ci variable recursion
    - export BUILD_ARGS="--build-arg=BASE_IMAGE=$FRONTEND_BASE_IMAGE"
  only: &frontend-only
    changes:
      - frontend/**/*

frontend-storybook-image:
  extends: .kaniko-build-template
  variables:
    COMPONENT: $FRONTEND_STORYBOOK_COMPONENT
    VERSION: $FRONTEND_STORYBOOK_VERSION
    CONTEXT: "frontend"
    DOCKERFILE: "frontend/Dockerfile-storybook"
  before_script:
    # it needs to be here due to a limit on gitlab ci variable recursion
    - export BUILD_ARGS="--build-arg=BASE_IMAGE=$FRONTEND_STORYBOOK_BASE_IMAGE"
  only: &frontend-only
    changes:
      - frontend/**/*
