version: '3.3'
services:
  traefik:
    image: "traefik:v2.6.1"
    restart: unless-stopped
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.network=gateway"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=adam.bisek@inventi.cz"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      # Dashboard reroute to HTTP port 
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.%MULTIDEPLOY_HOST%`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.middlewares=compression,basic-auth"
      # Compression
      - "traefik.http.middlewares.compression.compress=true"
      # Obfuscate server tokens
      - "traefik.http.middlewares.secure-headers.headers.customresponseheaders.X-Powered-By=inventi"
      - "traefik.http.middlewares.secure-headers.headers.customresponseheaders.Server=inventi"
      # Security
      - "traefik.http.middlewares.secure-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.secure-headers.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.secure-headers.headers.customresponseheaders.X-Frame-Options=deny"
      - "traefik.http.middlewares.secure-headers.headers.customresponseheaders.X-XSS-Protection=1; mode=block"
      - "traefik.http.middlewares.secure-headers.headers.customresponseheaders.X-Content-Type-Options=nosniff"
      # Basic auth
      - "traefik.http.middlewares.basic-auth.basicauth.users=traefik:$$apr1$$e4CRLlHd$$4F9s8RHs9z3GcctPOWmUz."
      - "traefik.http.middlewares.basic-auth.basicauth.removeheader=true"
      # Error pages
      - "traefik.http.middlewares.errorpages.errors.status=400-599"
      - "traefik.http.middlewares.errorpages.errors.service=error"
      - "traefik.http.middlewares.errorpages.errors.query=/{status}.html"
      # HTTPS redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
  error:
    restart: unless-stopped
    image: guillaumebriday/traefik-custom-error-pages
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error.rule=PathPrefix(`/`)"
      - "traefik.http.routers.error.priority=1"
      - "traefik.http.routers.error.service=error"
      - "traefik.http.services.error.loadbalancer.server.port=80"
      - "traefik.http.routers.error.entrypoints=web,websecure"
  # for immediate SSL cert challenge
  traefik-whoami:
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.traefik-whoami.rule=Host(`%APP_HOST%`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.traefik-whoami.priority=20"
      - "traefik.http.routers.traefik-whoami.entrypoints=web"
      - "traefik.http.routers.traefik-whoami.middlewares=redirect-to-https,errorpages"
      # HTTPS
      - "traefik.http.routers.traefik-whoami-secured.tls=true"
      - "traefik.http.routers.traefik-whoami-secured.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-whoami-secured.rule=Host(`%APP_HOST%`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.traefik-whoami-secured.middlewares=traefik-whoami-secured-stripprefix"
      - "traefik.http.middlewares.traefik-whoami-secured-stripprefix.stripprefix.prefixes=/whoami"
      - "traefik.http.routers.traefik-whoami-secured.priority=20"
      - "traefik.http.routers.traefik-whoami-secured.entrypoints=websecure"
      - "traefik.http.routers.traefik-whoami-secured.middlewares=errorpages"

networks:
    default:
        external:
            name: "gateway"
