version: '3.3'
services:
  app-fe:
    restart: unless-stopped
    image: $FRONTEND_IMAGE
    environment:
      - APP_ENV=develop
    env_file:
      - .env
    networks:
      - "gateway"
      - "default"
    links:
      # ensure that docker route to container within this docker-compose; without this, docker will randomly route to any container with this name
      # that could be a problem, when running multiple environments (docker-compose) on same machine
      # it is because all docker-compose sits on same network (for the sake of traefik routing)
      - app-be
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.$ENV_NAME-app-fe.loadbalancer.server.port=3000"
      - "traefik.http.routers.$ENV_NAME-app-fe.rule=Host(`%ENV_NAME%.%MULTIDEPLOY_HOST%`) && PathPrefix(`/`)"
      - "traefik.http.routers.$ENV_NAME-app-fe.priority=10"
      - "traefik.http.routers.$ENV_NAME-app-fe.entrypoints=web"
      - "traefik.http.routers.$ENV_NAME-app-fe.service=$ENV_NAME-app-fe"
      - "traefik.http.routers.$ENV_NAME-app-fe.middlewares=compression,secure-headers,errorpages"
    logging:
      # by default docker logs until no space left on hdd; we wanna set limit
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
  app-be:
    restart: unless-stopped
    image: $BACKEND_IMAGE
    environment:
      - APP_ENV=develop
    env_file:
      - .env
    volumes:
      - ./.volumes/be-uploads:/app/uploads
    networks:
      - "gateway"
      - "default"
    links:
      # ensure that docker route to container within this docker-compose; without this, docker will randomly route to any container with this name
      # that could be a problem, when running multiple environments (docker-compose) on same machine
      # it is because all docker-compose sits on same network (for the sake of traefik routing)
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.$ENV_NAME-app-be.loadbalancer.server.port=4000"
      - "traefik.http.routers.$ENV_NAME-app-be.rule=Host(`%ENV_NAME%.%MULTIDEPLOY_HOST%`) && PathPrefix(`/graphql`)"
      - "traefik.http.routers.$ENV_NAME-app-be.priority=11"
      - "traefik.http.routers.$ENV_NAME-app-be.entrypoints=web"
      - "traefik.http.routers.$ENV_NAME-app-be.service=$ENV_NAME-app-be"
      - "traefik.http.routers.$ENV_NAME-app-be.middlewares=compression,secure-headers,errorpages"
    logging:
      # by default docker logs until no space left on hdd; we wanna set limit
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    depends_on:
      - db
  db:
    image: $DATABASE_IMAGE
    restart: always
    environment:
      TZ: 'Europe/Prague'
      PGTZ: 'Europe/Prague'
    env_file:
      - .env
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
  frontend-storybook:
    image: $FRONTEND_STORYBOOK_IMAGE
    restart: always
    networks:
      - "gateway"
      - "default"
    labels:
      # HTTP
      - "traefik.enable=true"
      - "traefik.http.services.$ENV_NAME-frontend-storybook.loadbalancer.server.port=6006"
      - "traefik.http.routers.$ENV_NAME-frontend-storybook.rule=Host(`storybook.%ENV_NAME%.%MULTIDEPLOY_HOST%`)"
      - "traefik.http.routers.$ENV_NAME-frontend-storybook.entrypoints=web"
      - "traefik.http.routers.$ENV_NAME-frontend-storybook.service=$ENV_NAME-frontend-storybook"
      - "traefik.http.routers.$ENV_NAME-frontend-storybook.middlewares=compression"

  # You can turn on adminer on develop, if you want to; otherwise feel free to delete
  # adminer:
  #   image: dockette/adminer
  #   restart: always
  #   networks:
  #     - "gateway"
  #     - "default"
  #   labels:
  #     # HTTP
  #     - "traefik.enable=true"
  #     - "traefik.http.services.$ENV_NAME-adminer.loadbalancer.server.port=80"
  #     - "traefik.http.routers.$ENV_NAME-adminer.rule=Host(`adminer.%ENV_NAME%.%MULTIDEPLOY_HOST%`)"
  #     - "traefik.http.routers.$ENV_NAME-adminer.entrypoints=web"
  #     - "traefik.http.routers.$ENV_NAME-adminer.service=$ENV_NAME-adminer"
  #     - "traefik.http.routers.$ENV_NAME-adminer.middlewares=compression,secure-headers,errorpages"
  #     # HTTPS
  #     - "traefik.http.routers.adminer-secured.tls=true"
  #     - "traefik.http.routers.adminer-secured.tls.certresolver=myresolver"
  #     - "traefik.http.services.adminer-secured.loadbalancer.server.port=80"
  #     - "traefik.http.routers.adminer-secured.rule=Host(`adminer.%ENV_NAME%.%MULTIDEPLOY_HOST%`)"
  #     - "traefik.http.routers.adminer-secured.entrypoints=websecure"
  #     - "traefik.http.routers.adminer-secured.service=adminer-secured"
  #     - "traefik.http.routers.adminer-secured.middlewares=compression,secure-headers,errorpages"

networks:
  gateway:
    external:
      name: gateway
