api:
  dashboard: true
  insecure: true

# log:
#   level: DEBUG

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/routes.yml
    watch: true

entryPoints:
  web:
    address: :80
