locals {
  defaults = {
    # identifier = name of RDS instance or random
    # name = name of DB instance
    # instance_class = type of RDS instance
    # username =
    # password =
    # port =
    # allocated_storage = allocated storage in GB
    # engine = postgresql
    # engine_version = version of engine
    storage_type = null
    storage_encrypted = false
    kms_key_id = null
    replicate_source_db = null
    license_model = null
    iam_database_authentication_enabled = false
    domain = null
    domain_iam_role_name = null
    skip_final_snapshot = false
    snapshot_identifier = null
    copy_tags_to_snapshot = false
    final_snapshot_identifier = null
    final_snapshot_identifier_prefix = "final"
    vpc_security_group_ids = []
    availability_zone = null
    multi_az = false
    iops = 0
    publicly_accessible = false

    monitoring_interval = 0
    monitoring_role_arn = null
    monitoring_role_name = "rds-monitoring-role"
    create_monitoring_role = false

    allow_major_version_upgrade = false
    auto_minor_version_upgrade = true
    apply_immediately = false
    maintenance_window = "Sun:03:00-Sun:05:00"
    backup_retention_period = null
    backup_window = "01:46-02:46"
    s3_import = null
    tags = {}
    db_instance_tags = {}
    db_option_group_tags = {}
    db_parameter_group_tags = {}
    db_subnet_group_tags = {}
    create_db_subnet_group = true
    db_subnet_group_name = ""
    db_subnet_group_use_name_prefix = true
    db_subnet_group_description = ""
    subnet_ids = []
    create_db_parameter_group = true
    parameter_group_name = null
    parameter_group_use_name_prefix = true
    parameter_group_description = ""
    family = ""
    parameters = []
    create_db_option_group = true
    option_group_name = null
    option_group_use_name_prefix = true
    option_group_description = ""
    major_engine_version = ""
    options = []
    create_db_instance = true
    timezone = null
    character_set_name = null
    enabled_cloudwatch_logs_exports = []
    timeouts = {
      create = "40m"
      update = "80m"
      delete = "40m"
    }
    option_group_timeouts = {
      delete = "15m"
    }
    deletion_protection = false
    performance_insights_enabled = false
    performance_insights_retention_period = 7
    performance_insights_kms_key_id = null
    max_allocated_storage = 0
    ca_cert_identifier = null
    delete_automated_backups = true
    create_random_password = false
    random_password_length = 10
  }
  cfg = merge(local.defaults, var.configuration)
}