---
- name: Ensure group "docker" exists
  become: true
  group:
    name: docker
    state: present

- name: Add deploy user
  become: true
  user:
    name: "{{ deployUser }}"
    comment: deploy dea middleware
    group: root
    groups: docker
    shell: /bin/bash

# for having sudo without password
- name: Add deploy user to sudoers
  lineinfile:
    path: /etc/sudoers.d/{{deployUser}}
    line: "{{deployUser}} ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

# This is not 100% secure having this in repo, even though that is only the public key
- name: Set authorized key took from file
  authorized_key:
    user: "{{deployUser}}"
    state: present
    key: "{{deployPublicKey}}"

- name: Install docker
  apt: name=docker state=present update_cache=yes
  notify: restart docker

# https://stackoverflow.com/questions/50151833/cannot-login-to-docker-account
- name: Fix docker login
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - gnupg2
    - pass

- name: Install docker-compose
  apt: name=docker-compose state=present update_cache=yes
