entity: Product
items:
  product{1..9}:
    name: '{{name.firstName}}'
    availableCount: '{{datatype.number}}'
    description: '{{lorem.sentence}}'
    productTags: 
      - '@productTag{1..5}' # one of the array
      - '@productTag{6..9}' # one of the array

  product:
    name: 'Vladimir'
    availableCount: 10
    description: '{{lorem.sentence}}'
