locals {
  defaults = {
    create = true
    # vpc_id = 
    # name =
    use_name_prefix = false
    description = "Security Group managed by Terraform"
    revoke_rules_on_delete = false
    tags = {}
    ingress_rules = []
    ingress_with_self = []
    ingress_with_cidr_blocks = []
    ingress_with_ipv6_cidr_blocks = []
    ingress_with_source_security_group_id = []
    ingress_cidr_blocks = []
    ingress_ipv6_cidr_blocks = []
    ingress_prefix_list_ids = []
    computed_ingress_rules = []
    computed_ingress_with_self = []
    computed_ingress_with_cidr_blocks = []
    computed_ingress_with_ipv6_cidr_blocks = []
    computed_ingress_with_source_security_group_id = []
    number_of_computed_ingress_rules = 0
    number_of_computed_ingress_with_self = 0
    number_of_computed_ingress_with_cidr_blocks = 0
    number_of_computed_ingress_with_ipv6_cidr_blocks = 0
    number_of_computed_ingress_with_source_security_group_id = 0
    egress_rules = []
    egress_with_self = []
    egress_with_cidr_blocks = []
    egress_with_ipv6_cidr_blocks = []
    egress_with_source_security_group_id = []
    egress_cidr_blocks = ["0.0.0.0/0"]
    egress_ipv6_cidr_blocks = ["::/0"]
    egress_prefix_list_ids = []
    computed_egress_rules = []
    computed_egress_with_self = []
    computed_egress_with_cidr_blocks = []
    computed_egress_with_ipv6_cidr_blocks = []
    computed_egress_with_source_security_group_id = []
    number_of_computed_egress_rules = 0
    number_of_computed_egress_with_self = 0
    number_of_computed_egress_with_cidr_blocks = 0
    number_of_computed_egress_with_ipv6_cidr_blocks = 0
    number_of_computed_egress_with_source_security_group_id = 0
  }
  cfg = merge(local.defaults, var.configuration)
}